import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'

/**
 * Two outputs from the same source:
 *
 * - dist/ (index.html + app.js): a standalone page for local work (`npm start`). Not committed.
 * - ../../snippets/CheckoutPreview.jsx: what the docs use. Mintlify serves no .html and injects
 *   every .js in the repo into all pages, so the page is inlined into an `<iframe srcdoc>` inside a
 *   JSX snippet. The iframe keeps the preview's fetch interceptor and the SDK off the docs page.
 */

const SNIPPET = '../../snippets/CheckoutPreview.jsx'
const SCRIPT_TAG = '<script src="./app.js" defer></script>'

await rm('dist', { recursive: true, force: true })
await mkdir('dist', { recursive: true })

const result = await build({
  entryPoints: ['src/main.ts'],
  bundle: true,
  format: 'iife',
  target: 'es2020',
  minify: true,
  write: false,
})
const js = result.outputFiles[0].text
const html = await readFile('src/index.html', 'utf8')
if (!html.includes(SCRIPT_TAG)) throw new Error(`index.html must load the bundle with ${SCRIPT_TAG}`)

await writeFile('dist/app.js', js)
await writeFile('dist/index.html', html)

// `</script` inside the inlined bundle would close the tag early
const inlineScript = (code) => `<script>${code.replace(/<\/script/gi, '<\\/script')}</script>`
const embedded = html.replace(
  SCRIPT_TAG,
  () => inlineScript('window.__YUNO_PREVIEW__={embedded:true}') + inlineScript(js),
)

const snippet = `// Generated by tools/checkout-preview (npm run build). Do not edit by hand.
//
// Interactive checkout preview: the production Yuno Web SDK with a local mock backend, isolated in
// an <iframe srcdoc>. Source, tests and how it works: tools/checkout-preview/README.md.

export const CheckoutPreview = ({ height = 880 }) => {
  // Inside the component: Mintlify only keeps a snippet's exports, so module-level constants are dropped
  const html = ${JSON.stringify(embedded)}
  const frame = useRef(null)

  // Follow the docs' light/dark mode (Mintlify toggles the "dark" class on <html>)
  const syncTheme = () => {
    const doc = frame.current?.contentDocument
    if (!doc?.documentElement) return
    doc.documentElement.dataset.theme = document.documentElement.classList.contains('dark') ? 'dark' : 'light'
  }

  useEffect(() => {
    const observer = new MutationObserver(syncTheme)
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] })
    return () => observer.disconnect()
  }, [])

  return (
    <iframe
      ref={frame}
      title="Yuno checkout preview"
      srcDoc={html}
      onLoad={syncTheme}
      className="not-prose"
      style={{ width: '100%', height, border: '1px solid rgba(128, 128, 128, 0.25)', borderRadius: 16 }}
    />
  )
}
`

await writeFile(SNIPPET, snippet)
console.log(`[build] dist/ + ${SNIPPET} (${Math.round(snippet.length / 1024)} KB)`)
